bskel: Put set -x in a separate line

diff --git a/common/.local/my_bin/bskel b/common/.local/my_bin/bskel
--- a/common/.local/my_bin/bskel
+++ b/common/.local/my_bin/bskel
@@ -43,5 +43,6 @@ touch "${path}"
 echo '#!/usr/bin/env bash' >> "${path}"
 echo '#' >> "${path}"
 echo '' >> "${path}"
-echo 'set -xeuo pipefail' >> "${path}"
+echo 'set -euo pipefail' >> "${path}"
+echo 'set -x' >> "${path}"
 chmod +x "${path}"
